<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerApxwkmq\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerApxwkmq/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerApxwkmq.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerApxwkmq\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerApxwkmq\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Apxwkmq',
    'container.build_id' => '50b8edfc',
    'container.build_time' => 1553286536,
));
